### ISSUE TITLE
Readme link broken

### ISSUE THREAD

**Issue by stephantul** [treyturner/analogue-pocket-patches#2]
Hi! 

The README link to the `more info` is broken. i.e., `https://strt-slct.com/analogue-pocket-patches` no longer seems to exist.
I went to the website, but there's no obvious clickable link to an alternative, so maybe it got deleted.

Bye!

**Comment by treyturner** [comment]
Thanks! I put these documents into a reasonable final state in https://github.com/treyturner/analogue-pocket-patches/compare/b0f175e6b48991eb91f0616ff2dfe6c679188a6f...main and will archive the repo.
